### ISSUE TITLE
error not returned !?

### ISSUE THREAD

**Issue by mahdifarzadi** [gocastsian/adamak#4]
https://github.com/gocastsian/adamak/blob/78cb133c6d43cb642d3a82889e49fe5c77c2c760/adapter/store/user.go#L21

why didn't you return nil instead of empty user entity?
and why error is nil?

**Comment by gocastsian** [comment]
We discussed about it in third session of GoCasts weekly, you can watch it [here](https://www.youtube.com/watch?v=hSffw-yumMk).
The code you mentioned have been fixed.
